version: "3.9"

services:
  docker-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker_proxy
    environment:
      CONTAINERS: 1
      SERVICES: 1
      NETWORKS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal

  traefikator:
    image: ghcr.io/myrenic/traefikator:b862509
    container_name: traefikator
    environment:
      CERT_NAME: "${CERT_NAME:-localhost}"
      CERT_DAYS: "${CERT_DAYS:-90}"
      CERT_RENEW_DAYS: "${CERT_RENEW_DAYS:-30}"
      DELETE_ON_STARTUP: "${DELETE_ON_STARTUP:-false}"
      CERT_TRAEFIK_PATH: "${CERT_TRAEFIK_PATH:-/certs}"
    volumes:
      - traefik_certs:/app/certs
      - traefik_dynamic:/app/dynamic
    networks:
      - internal
    depends_on:
      - docker-proxy
    restart: "no"

  traefik:
    image: traefik:v3.6
    container_name: traefik
    command:
      - "--api.dashboard=false"
      - "--api.insecure=false"
      - "--providers.docker.endpoint=tcp://docker-proxy:2375"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik_certs:/certs
      - traefik_dynamic:/etc/traefik/dynamic:ro
    depends_on:
      - docker-proxy
      - traefikator
    networks:
      - internal
      - external

volumes:
  traefik_certs:
  traefik_dynamic:

networks:
  internal:
  external:
    external: true
